package pl.malirz.vshop.product.command

import java.math.BigDecimal

/**
 * Main model representing the product. Each instance of this object represents a product in the Shop.
 * Each product has a unique business code and also quantity and price in the shop.
 *
 * <<AggregateRoot>>
 */
class Product(
    /** An internal identifier generated by the system. */
    val id: String,
    /** Unique business code. */
    val code: String,
    val name: String,
    val description: String?,
    /** Current price. */
    val price: BigDecimal?,
    /** The number of available products in the shop, that client can buy. */
    val quantity: Int?,
    val version: Long? = 1L
)

