ALTER SESSION SET CONTAINER = XEPDB1;

-- VSHOP application user
CREATE USER vshop IDENTIFIED BY vshop;
ALTER USER vshop QUOTA UNLIMITED ON users;
GRANT CREATE SESSION TO vshop;

GRANT SELECT ANY TABLE TO vshop;
GRANT INSERT ANY TABLE TO vshop;
GRANT UPDATE ANY TABLE TO vshop;
GRANT DELETE ANY TABLE TO vshop;

-- VSHOPCACHE user dedicated for Infinispan to persist the cache
CREATE USER vshopcache IDENTIFIED BY vshopcache;
ALTER USER vshopcache QUOTA UNLIMITED ON users;
GRANT CREATE SESSION TO vshopcache;

GRANT CREATE TABLE TO vshopcache;
GRANT SELECT ANY TABLE TO vshopcache;
GRANT INSERT ANY TABLE TO vshopcache;
GRANT UPDATE ANY TABLE TO vshopcache;
GRANT DELETE ANY TABLE TO vshopcache;
